### ISSUE TITLE
Causes Optifine Options to Vanish

### ISSUE THREAD

**Issue by NovaViper** [jaredlll08/Visualize#2]
I have Forge 14.21.1.2443 with Optifine HD C5 for 1.12. 

When I load up the game with both this mod and Optifine, I can't find any of the Optifine settings, as if I haven't installed the mod at all. The only one showing in Mipmap Levels.

**Comment by NovaViper** [comment]
I also reported this issue to [Optifine](https://github.com/sp614x/optifine/issues/834)

**Comment by jaredlll08** [comment]
The mods are literally incompatible, there isn't a fix, also Tbh, I don't
even know if visualize works on 1.12, havnt had the time to test

**Comment by NovaViper** [comment]
Oh, I didn't realize that they were incompatible. Huh, I'm curious why though, as this one is suppose to see capture settings?
